name: bajayt
version: 0.1.0
summary: Baja YT
description: Download Youtube videos and audios

confinement: strict
base: core22
grade: stable

slots:
  dbus-bajayt: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.bajayt # adjust accordingly to your app name and

apps:
  bajayt:
    command: bajayt
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    - home
    slots:
      - dbus-bajayt
parts:
  bajayt:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

plugs:
  dot-downloads:
    interface: personal-files
    read:
      - $HOME/Downloads
